### ISSUE TITLE
Question for help

### ISSUE THREAD

**Issue by BlueForrest** [corncobb/LS3766R-Raspberry-Pi#1]
I’m looking for help on a project I started for my old jukebox.
I have an old jukebox and I would like to show a picture of the artist for the currently playing song.

My jukebox has a selection wheel that rotates slowly from one position to another.  (average of 12 seconds for a complete cycle)  
1 complete cycle is 100 counts as there are 100 records.

My idea is to put an encoder and count every click/position of the motor.
So when it turns, I start counting up, when reach starting point (I have a switch for that) the counter is reset and starts again.
Doing this I would perfectly know that song 34 is selected and I can show the picture or do anything else.

So I purchased a Raspberry PI4 and a Rotary Optical Encoder  type ENC1J-D28-L00100L
This is a  2-bit quadrature code, Channel A leads Channel B by 90 º (electrical) clockwise rotation 
Resolution = 100 cycles per revolution / Voltage = 5.0 VDC ±0.25  

Now my problem is to get an accurate count.
I have tried already some python code I found, but non off them works properly.  Too often false detections ect…
I started to google and came across your video on youtube.
It seems very interesting to use the LS7366R Quadrature Counter which I believe that could work with my encoder.  Now I'm trying to understand your code.
I know how to install “spidev” and enable SPI on the raspberry.
But I don’t understand what I need to do with following comment/instructions you mentioned in the code :

# Usage: import LS7366R then create an object by calling enc = LS7366R(CSX, CLK, BTMD)
# CSX is either CE0 or CE1, CLK is the speed, BTMD is the byte mode 1-4 the resolution of your counter.
# example: lever.Encoder(0, 1000000, 4)
# These are the values I normally use.

Can you give me some more explanation on this.  (Explain practically what I need to do)
Do you mean I have to set the data in line 126 of your code according my encoder.  

in my case it would be 
encoder = LS7366R(0, 1000000, 2)   - but what about the CLK? is that the motor speed or is it the frequency of updating/sending data to the raspberry?

Furthermore as I have a 2-bit quadrature encoder, I should set variable
 QUADRATURE_COUNT_MODE = 0x02  instead of 0x00  - is that correct?

Hope you can help me clearing this out.
(forgive me asking stupid questions as I’m newbie in programming & electronics)

Sincere regards,
Johan

Picture of my current diagram, where the level shifter should be replaced with an LS7366R single board
![image](https://user-images.githubusercontent.com/33237156/75162868-86c64e80-571e-11ea-9df6-0fe85f36750f.png)

**Comment by corncobb** [comment]
Hi Johan,

First, because you have a 2-bit quadrature encoder, you need to set QUADRATURE_COUNT_MODE = 0x02.

CLK is the frequency of updating/sending data and is in HZ. In the code it is written as `self.spi.max_speed_hz = CLK #Speed of clk (modifies speed transaction) `

You can learn more about the CLK or max_speed_hz from these articles here but I don't think you will need to adjust that value. 1000000 should be good enough.

https://projects.drogon.net/understanding-spi-on-the-raspberry-pi/
https://www.takaitra.com/spi-device-raspberry-pi/

If your setup is going to be `encoder = LS7366R(0, 1000000, 2)`, that means your CSX is going to CE0 which is GPIO 8 on your Raspberry Pi 4, the transaction speed is 1000000 HZ and your bytemode is 2. Bytemode ranges from 1 - 4 and I recommend looking at the datasheet here: https://www.superdroidrobots.com/product_info/LS7366R.pdf

My bytemode was set to 4 in my case.

Lets start here and please come back if you have anymore problems.

**Comment by BlueForrest** [comment]
Hi,  Thanks for the reply. It makes a lot more clear to me.
